# Generated by Django 3.0.8 on 2020-08-05 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200803_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
