# Generated by Django 3.0.8 on 2020-08-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SK', 'Skate'), ('SP', 'Sports'), ('CA', 'Casual'), ('SO', 'Socks')], max_length=2),
        ),
    ]
