# Generated by Django 3.0.8 on 2020-08-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200811_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('CA', 'Casual'), ('SP', 'Sports'), ('SK', 'Skate')], max_length=2),
        ),
    ]
